apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - roost-worker2
  containers:
  - image: busybox
    command:
    - "sleep"
    - "3600"
    name: hpc
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /tmp/data
      # type field is optional
      type: Directory
